flags: {}
extra-package-dbs: []
packages:
- '.'
- location: h-gpgme
  extra-dep: true
extra-deps:
- bindings-gpgme-0.1.6
- daemons-0.2.1
- esqueleto-2.4.3
- persistent-2.2.4.1
- persistent-sqlite-2.2.1
- persistent-template-2.1.8.1
resolver: lts-7.14
